[Buddy3]
Name=127.0.0.1
Host=127.0.0.1
Port=12345

[General]
Count=3

[Buddy0]
Name=ani
Host=ip
Port=պորտ

[Buddy1]
Name=norayr
Host=201:af82:9f2f:7809:be0c:360a:1587:6be7
Port=12455

[Buddy2]
Name=loopback
Host=::1
Port=8080
